<a href="https://colab.research.google.com/github/KD-kAnEsHi/Mini-Projects/blob/main/Intro_To_Deep_Learning___Chapter_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
torch.__version__

'2.6.0+cu124'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() # Retrived ths the number inside of a tensor

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim     # Returns the total number of [] is in the tensor

1

In [ ]:
vector.shape   # shape return the number of items inside the rectangular boxes

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 5, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# creates matrix / set of tensors with random numbers
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9504, 0.4689, 0.5719, 0.6139],
         [0.0840, 0.5759, 0.5536, 0.4501],
         [0.4740, 0.8627, 0.6162, 0.2882]]),
 torch.float32)

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# tensor full of zeros, used when masking NN during training etcc
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3, 4))  # I belive only zero and one are build into pytorch
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# SImilar to python, we can map througha list of sort using a range (arange)

zero_to_ten_deprecated = torch.range(0, 0)

zero_to_ten = torch.arange(0, 10, 1)    # start from zero, end at 10, and iterate by 1
zero_to_ten

/tmp/ipython-input-18-1549496244.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 0)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# deteming detatypes
float_32 = torch.tensor([1.0, 3.0, 8.2], dtype=None, device=None, requires_grad=False)
float_32.shape, float_32.dtype, float_32.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# we can specifiy the float of a tensor
float_64 = torch.tensor([4.3, 6.2, 19.3], dtype=torch.float64)
float_64.dtype


torch.float64

In [ ]:
# Operation with tensors

tensor = torch.tensor([1, 2, 5])
tensor += 100
print(tensor)

second_tensor = torch.multiply(tensor, 10)
print(second_tensor)

tensor([101, 102, 105])
tensor([1010, 1020, 1050])


In [ ]:
new_tensor = second_tensor * tensor # works
print(new_tensor)

tensor([102010, 104040, 110250])


In [ ]:
# We have to tranposse matrix before multiplying them, else we will get errors
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

print(tensor_A)
print(tensor_B)
tensor_out = tensor_A @ tensor_B.T
tensor_out

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x = torch.arange(0, 2000, 10)
x

tensor([   0,   10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
         120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,  230,
         240,  250,  260,  270,  280,  290,  300,  310,  320,  330,  340,  350,
         360,  370,  380,  390,  400,  410,  420,  430,  440,  450,  460,  470,
         480,  490,  500,  510,  520,  530,  540,  550,  560,  570,  580,  590,
         600,  610,  620,  630,  640,  650,  660,  670,  680,  690,  700,  710,
         720,  730,  740,  750,  760,  770,  780,  790,  800,  810,  820,  830,
         840,  850,  860,  870,  880,  890,  900,  910,  920,  930,  940,  950,
         960,  970,  980,  990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070,
        1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190,
        1200, 1210, 1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310,
        1320, 1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430,
        1440, 1450, 1460, 1470, 1480, 14

In [ ]:
print(x.min())
print(x.type(torch.float32).mean())
print(x.max())

tensor(0)
tensor(995.)
tensor(1990)


In [ ]:
x.dtype

torch.int64

In [ ]:
x = torch.arange(1, 22, 2)
x, x.shape

(tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21]), torch.Size([11]))

In [ ]:
z = x.reshape(1, 11)
z, z.shape

(tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21]]), torch.Size([1, 11]))

In [ ]:
z = x.view(1, 11)
z, z.shape

(tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21]]), torch.Size([1, 11]))

In [ ]:
# Stacking tensors on top of themselves haha
new_tensors = torch.arange(1 , 20, 2)
stacked = torch.stack([new_tensors, new_tensors, new_tensors, new_tensors], dim=0)
stacked

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [ ]:
# stack, for adding tensors
# squeeze for removing tensors
print(f"Previous tensor: {stacked}")
print(f"Previous shape: {stacked.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = stacked.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])
Previous shape: torch.Size([4, 10])

New tensor: tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])
New shape: torch.Size([4, 10])


In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Next:

PYTOCH WALKTHROUGH.  - Starting from "Reshaping, stacking, squeezing and unsqueezing"

In [7]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [8]:
x_reshape = x.reshape(1, 7)   # adds an extra dimention
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [9]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [11]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [17]:
x_stacked = torch.stack([x, x, x, x], dim=1)      # stack dimensions on to each other
x_stacked                                         # 0: row, 1: col

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [18]:
x_original = torch.rand(size=(224, 224, 3))       # originals.
x_permuted = x_original.permute(2, 0, 1)          # news axis: (3, 224, 224)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

INDEXING

In [19]:
x = torch.arange(1, 10).reshape(1, 3, 3)          # indexing arange using .reshape
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Pytorch and Numpy

In [21]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [23]:
tensor = torch.ones(10)                           # We cabn move tensor from pytorhc to numpy
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

REPRODUCTIVITY : RANDOMNESS ON DIFFERENT DEVICES

In [31]:
import random

RANDOM_SEED = 90                                  # seeds produce same result across different platforms
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [34]:
torch.manual_seed(0)
"""" This sets the seed for PyTorch’s internal randomness, so that operations like random tensor generation or weight initialization are repeatable.
It doesn’t affect all “apps” in your program — just PyTorch operations.  """

random.seed(0)
""" Sets the seed for Python’s built-in random module so that results from random.* functions are repeatable."""

' Sets the seed for Python’s built-in random module so that results from random.* functions are repeatable.'

CUDA on laptop

Making useof Cuda

In [40]:
torch.cuda.is_available()                                       # check whether cuda is available for use

False

In [41]:
device = "cuda" if torch.cuda.is_available() else "cpu"         # use which ever is avalable
device
# device = "mps" if torch.cuda.is_available() else "cpu"        # Use 'mps' when using M1...

'cpu'

In [44]:
tensor = torch.tensor([1, 2, 3])
tensor_on_device = tensor.to(device)                            # Run tensor on what ever device is available
tensor_on_device

tensor([1, 2, 3])

Exercise:

Chapter 1: Exercise - LETS GOOO

In [51]:
# Exersice
# 2
rand_tensor = torch.rand(7, 7)
# 3
rand_tensor_2 = torch.rand(1, 7)
mult_tensor = rand_tensor @ rand_tensor_2.T
mult_tensor

tensor([[1.1355],
        [1.2708],
        [1.3344],
        [0.9095],
        [2.0434],
        [1.4647],
        [0.8178]])

In [55]:
# 4
torch.manual_seed(0)

# 5
rand_tensor = torch.rand(7, 7)
rand_tensor_2 = torch.rand(1, 7)
mult_tensor = rand_tensor @ rand_tensor_2.T
mult_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [7]:
# 6
torch.cuda.manual_seed(1234)

# 7
rand_tensor = torch.rand(2, 3, device="cuda")
rand_tensor_2 = torch.rand(2, 3, device="cuda")
mult_tensor = rand_tensor @ rand_tensor_2.T
mult_tensor, mult_tensor.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

In [12]:
# 9
print(f"min: {mult_tensor.min()}")
print(f"max: {mult_tensor.max()}")

min: 0.27863210439682007
max: 0.7667766809463501


In [13]:
# 10
torch.manual_seed(0)

new_tensor = torch.rand(1, 1, 1, 10)
new_tensor

tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
           0.4556, 0.6323]]]])

In [22]:
new_tensor.squeeze(0)


tensor([[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
          0.4556, 0.6323]]])

CHAPTER 2 : LETS GO BRODY111111111111

HGOOOOOOO